FROM node:8-alpine as builder

COPY package.json package-lock.json ./

RUN npm set progress=false && npm config set depth 0 && npm cache clean --force

## Storing node modules on a separate layer will prevent unnecessary npm installs at each build
RUN npm install -g @angular/cli

RUN npm i && mkdir /ng-app && cp -R ./node_modules ./ng-app



WORKDIR /ng-app

COPY . .

CMD ["ng", "serve", "--host", "0.0.0.0"]
